'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {webcrypto}=require('node:crypto');
const AB=require('../js/address-book');
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const book=AB.fromLegacy({cities:['Шевченко','Таромське'],streets:{'Шевченко':['Вул Шевченко'],'Таромське':['Вул Привокзальна','Новопокровська']}});
const [shev,tarom]=book.cities;
const [shevStreet,station,novo]=book.streets;
assert.notEqual(shev.id,shevStreet.id,'City and Street have separate UUIDs');
assert.equal(shevStreet.cityId,shev.id);
const original=station.id;
AB.update(book,'streets',original,{name:'Вулиця Привокзальна',aliases:['Вул Привокзальна','Привокзальна','Привокзальная','ул Привокзальная','вул. Привокзальна'],id:shev.id,cityId:shev.id});
AB.update(book,'cities',tarom.id,{aliases:['Таромское']});
AB.update(book,'streets',novo.id,{aliases:['Новопокровская']});
assert.equal(station.id,original,'rename retains identity');
assert.equal(station.cityId,tarom.id,'update cannot move street');
for(const alias of station.aliases){assert.deepEqual(AB.resolve(book,'Таромское',alias),{status:'ALIAS_EXACT',cityId:tarom.id,streetId:original});}
assert.equal(AB.resolve(book,'Таромське','Новопокровская').streetId,novo.id);
const second=AB.add(book,'streets',station.name,shev.id);
assert.notEqual(second.id,station.id,'same street name, different city');
assert.equal(AB.resolve(book,'Шевченко',station.name).streetId,second.id);
const ticket={id:'historical-ticket-007',city:'Таромське',street:'Вулиця Привокзальна',house:'3б',apartment:'1'};
const snapshot=JSON.stringify(ticket);
assert.equal(AB.resolve(book,ticket.city,ticket.street).status,'EXACT');
assert.equal(JSON.stringify(ticket),snapshot,'resolver never links or modifies historical tickets');
const duplicate=AB.add(book,'streets',station.name,tarom.id);
assert.equal(AB.resolve(book,ticket.city,ticket.street).status,'AMBIGUOUS','no automatic link');
assert.ok(AB.duplicateCandidates(book).some(ids=>ids.includes(original)&&ids.includes(duplicate.id)));
AB.update(book,'streets',duplicate.id,{active:false});
assert.equal(AB.resolve(book,ticket.city,ticket.street).status,'EXACT');
assert.equal(AB.resolve(book,'','x').status,'MALFORMED');
assert.equal(AB.resolve(book,'Невідоме','x').status,'NO_MATCH');
assert.equal(AB.resolve(book,{},'x').status,'MALFORMED');
AB.update(book,'cities',tarom.id,{active:false});
assert.equal(AB.resolve(book,'Таромське',station.name).status,'NO_MATCH');
assert.equal(book.streets.find(s=>s.id===original).active,true,'parent archive preserves child metadata');
assert.ok(!AB.projection(book).cities.includes('Таромське'));
AB.update(book,'cities',tarom.id,{active:true});
assert.equal(AB.resolve(book,'Таромське',station.name).streetId,original);
const exported=JSON.parse(JSON.stringify({addressBook:book,...AB.projection(book)}));
const imported=AB.importSettings(exported,{cities:[],streets:{}});
assert.deepEqual(imported.addressBook,book,'backup roundtrip retains all UUIDs including archives');
const legacy=AB.importSettings({cities:['Шевченко','Нове'],streets:{'Нове':['Вул Шевченко']}},imported);
assert.equal(legacy.addressBook.cities.find(c=>c.name==='Шевченко').id,shev.id);
assert.equal(legacy.addressBook.streets.find(s=>s.id===original).id,original);
assert.ok(legacy.addressBook.cities.some(c=>c.name==='Нове'),'legacy backup remains supported');
const deviceB=AB.fromLegacy({cities:['Шевченко'],streets:{'Шевченко':['Вул Шевченко']}});
assert.notEqual(deviceB.cities[0].id,shev.id);
const merged=AB.importSettings({addressBook:deviceB},imported).addressBook;
assert.equal(AB.resolve(merged,'Шевченко','Вул Шевченко').status,'AMBIGUOUS','two-device duplicates preserved');
assert.equal(merged.cities.length,book.cities.length+1);
assert.throws(()=>AB.importSettings({cities:['Шевченко'],streets:{'Шевченко':['Не прив’язувати'] }},{addressBook:merged}),/Неоднозначне/,'legacy import cannot pick one duplicate city UUID or silently lose streets');
AB.update(book,'streets',duplicate.id,{active:true,aliases:['Привокзальная']});
assert.equal(AB.resolve(book,'Таромское','Привокзальная').status,'AMBIGUOUS','alias exact must check every competing identity');
AB.update(book,'streets',duplicate.id,{active:false});
assert.throws(()=>AB.importSettings({addressBook:{version:2,cities:[],streets:[]}},imported));
const bad=AB.copy(book);bad.streets[0].cityId='missing';assert.throws(()=>AB.validate(bad));
assert.throws(()=>AB.add(book,'cities','test',null,{uuid:()=>shev.id}));
const poisoned=AB.fromLegacy(JSON.parse('{"cities":["__proto__"],"streets":{"__proto__":["constructor"]}}'));
assert.deepEqual(AB.projection(poisoned).streets.__proto__,['constructor']);
assert.equal({}.polluted,undefined);

// Exercise the actual UI transaction, reload persistence, quota failure and writer lock.
let disk=null,fail=false,writer=true;
const context={MTAddressBook:AB,settings:{cities:['Таромське'],streets:{'Таромське':['Вул Привокзальна']}},showToast(){},
  saveSettings(){if(!writer)return false;if(fail)throw new Error('QuotaExceededError');disk=JSON.stringify(context.settings);}};
vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/address-book-ui'),'utf8'),context);
assert.equal(context.mtAddressBookInitialize(),true);
const first=context.settings.addressBook.cities[0].id;
context.settings=JSON.parse(disk);
assert.equal(context.mtAddressBookInitialize(),true);
assert.equal(context.settings.addressBook.cities[0].id,first,'offline reload does not regenerate IDs');
const prior=JSON.stringify(context.settings),persisted=disk;
fail=true;assert.equal(context.mtAddressBookRemember('Інше','Вулиця'),false);
assert.equal(JSON.stringify(context.settings),prior);assert.equal(disk,persisted);
fail=false;writer=false;assert.equal(context.mtAddressBookRemember('Інше','Вулиця'),false);
assert.equal(JSON.stringify(context.settings),prior);assert.equal(disk,persisted);
assert.equal(JSON.stringify(ticket),snapshot,'existing ticket.id and text never change');
// Real settings persistence must preserve legacy data if identity data is damaged.
let settingsDisk=null;
const runtime={MTAddressBook:AB,settings:null,loadJSON:()=>({cities:['Legacy'],streets:{Legacy:['Street']},addressBook:{version:99}}),
  localStorage:{setItem:(_key,value)=>{settingsDisk=JSON.parse(value);}},MTSingleWriterLock:{warn:()=>true}};
vm.createContext(runtime);vm.runInContext(fs.readFileSync(require.resolve('../js/settings-core'),'utf8'),runtime);
runtime.settings=runtime.loadSettings();runtime.saveSettings();
assert.equal(settingsDisk.addressBook.version,99,'invalid identity data is preserved for recovery, not regenerated');
assert.deepEqual(settingsDisk.cities,['Legacy'],'corrupt book does not erase legacy view or abort ordinary settings persistence');
const large=AB.fromLegacy({cities:['Місто'],streets:{'Місто':Array.from({length:3000},(_,i)=>`Вулиця ${i}`)}});
assert.equal(AB.projection(large).streets['Місто'].length,3000,'bounded large legacy directory migration retains every street');
console.log('PASS AddressBook UUID identity, aliases, scopes, archives, conservative resolution, backup, offline and atomic writes');
