'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const files=['js/ai/ai-config.js','js/ai/ai-ticket-id.js','js/ai/ai-client.js','js/ai/ai-chat.js'];
const sb={console,setTimeout,clearTimeout,AbortController,Response,fetch};sb.globalThis=sb;vm.createContext(sb);for(const f of files)vm.runInContext(fs.readFileSync(f,'utf8'),sb,{filename:f});
const items=[{ticket_id:'A',address:'Карнаухівка, Вул Польова 14',type:'Ремонт'},{ticket_id:'B',address:"ВЧ, Пам'ятна 3",type:'Ремонт'}];
const qc={mode:'list',resolved_filters:{date_from:'01.10.2026',date_to:'05.10.2026',type:'Ремонт',coworker_exclude:'Женя',semantic:{entity:'onu',action:'install',profile:'onu_physical',category:'definite'}}};
function store(){const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
function setup(rows=items){let calls=0;const storage=store(),seen=[];
 const client=sb.MTAI.createClient({getConfig:()=>({backendUrl:'https://test.invalid',bearer:'synthetic'}),fetchImpl:async(_url,init)=>{calls++;const body=JSON.parse(init.body);return new Response(JSON.stringify({ai_contract_version:1,ok:true,answer:calls===1?'2 results':'245 repairs',total:calls===1?2:245,meta:{rounds:1},queryContext:qc,resultSet:calls===1?{version:1,id:'rs',chatSessionId:body.context.chatSessionId,createdAt:Date.now(),expiresAt:Date.now()+60000,total:rows.length,ticketIds:rows.map(i=>i.ticket_id)}:null,resultItems:calls===1?rows:[],referentTickets:rows.map(i=>({id:i.ticket_id,address:i.address,type:i.type}))}),{status:200});}});
 const make=()=>sb.MTAI.createChatController({client,storage,hooks:{assistant:o=>seen.push(o)}});
 return{client,storage,seen,make,calls:()=>calls};
}
(async()=>{
 let count=0;
 for(const [q,id] of [['открой вторую','B'],['открой первую','A'],['Памятная 3','B'],['ВЧ Памятная 3','B'],['Открой память на три','B'],['карнауховка полевая','A'],['эту вторую','B'],['покажи первую','A'],['2','B'],['відкрий другу','B']]){
  const s=setup(),chat=s.make();await chat.send('а ремонты Покажи пожалуйста');await chat.send(q);
  assert.equal(s.calls(),1,q+': must not make global query');assert.equal(s.seen[1].presentation?.ticket_id,id,q);assert.equal(s.seen[1].meta.rounds,0);assert.equal(s.seen[1].meta.toolCallsMade,0);
  assert.deepEqual(JSON.parse(s.storage.getItem('mtAiChatHistoryV1')).messages.at(-1).queryContext,qc);count++;
 }
 {const s=setup([{ticket_id:'A',address:'Памятная 3'},{ticket_id:'B',address:'Памятная 30'}]),chat=s.make();await chat.send('list');await chat.send('открой Памятная');assert.equal(s.calls(),1);assert.equal(s.seen[1].meta.clarification,true);assert.equal(s.seen[1].presentation,null);count++;await chat.send('открой вторую');assert.equal(s.seen.at(-1).presentation.ticket_id,'B');assert.equal(s.calls(),1);count++;}
 {const s=setup(),chat=s.make();await chat.send('list');await chat.send('открой Садовая 999');assert.equal(s.calls(),2,'no match permits legacy fallback');count++;}
 {const s=setup();await s.make().send('list');const chat=s.make();await chat.send('память на три');assert.equal(s.calls(),1,'list/address projection survives reload');assert.equal(s.seen.at(-1).presentation.ticket_id,'B');await s.make().send('открой карточку');assert.equal(s.calls(),1);assert.equal(s.seen.at(-1).presentation.ticket_id,'B');count+=2;}
 {const s=setup(),chat=s.make();await chat.send('list');await chat.send('открой 9');assert.equal(s.calls(),1,'out-of-range must clarify');assert.ok(s.seen.at(-1).meta.clarification);count++;}
 {const s=setup(),chat=s.make();await chat.send('list');await chat.send('Сколько ONU с Петей в августе?');assert.equal(s.calls(),2,'analytics is not navigation');count++;}
 {const s=setup(),chat=s.make();await chat.send('list');await chat.send('открой 0');assert.equal(s.calls(),1);assert.ok(s.seen.at(-1).meta.clarification);count++;}
 {const s=setup(),chat=s.make();await chat.send('list');await chat.send('открой id B');assert.equal(s.calls(),1);assert.equal(s.seen.at(-1).presentation.ticket_id,'B');count++;}
 {const s=setup();await s.make().send('list');const raw=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));raw.activeResultItems.forEach(i=>{i.masterNote='private';i.phone='secret';i.geoLat=1;});s.storage.setItem('mtAiChatHistoryV1',JSON.stringify(raw));await s.make().send('память на три');const persisted=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));assert.ok(persisted.activeResultItems.every(i=>!('masterNote' in i)&&!('phone' in i)&&!('geoLat' in i)));assert.equal(s.calls(),1);count++;}
 {const s=setup();await s.make().send('list');const raw=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));raw.activeResultItems=raw.activeResultItems.slice(1);raw.messages.at(-1).referentTickets=[];s.storage.setItem('mtAiChatHistoryV1',JSON.stringify(raw));await s.make().send('память на три');assert.equal(s.calls(),1);assert.ok(s.seen.at(-1).meta.clarification,'incomplete list cannot assert unique address');count++;}
 {const s=setup();await s.make().send('list');const raw=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));raw.activeResultSet.expiresAt=Date.now()-1;s.storage.setItem('mtAiChatHistoryV1',JSON.stringify(raw));await s.make().send('открой вторую');assert.equal(s.calls(),2,'expired set never resolves locally');count++;}
 {const s=setup(),chat=s.make();await chat.send('list');const raw=JSON.parse(s.storage.getItem('mtAiChatHistoryV1')),ctx={chatSessionId:raw.chatSessionId,resultSet:raw.activeResultSet,resultItems:items,queryContext:qc};assert.equal(s.client.resolveResultSetFollowUp('Памятная 30',ctx),null,'house numbers exact');assert.equal(s.client.resolveResultSetFollowUp('открой вторую',{...ctx,chatSessionId:'different-session'}),null);assert.equal(s.client.resolveResultSetFollowUp('с Женей',ctx),null,'no fuzzy roster matching');assert.equal(s.client.resolveResultSetFollowUp('открой вторую',{...ctx,queryContext:{...qc,resolved_filters:{...qc.resolved_filters,coworker:'Петя'}}}),null,'invalid contract does not bypass compatibility guard');count+=4;}
 {const s=setup(),chat=s.make();await chat.send('list');const raw=JSON.parse(s.storage.getItem('mtAiChatHistoryV1')),comparison={mode:'count',comparison:{periods:[{from:'01.09.2026',to:'30.09.2026'},{from:'01.08.2026',to:'31.08.2026'}]},resolved_filters:{semantic:qc.resolved_filters.semantic,coworker_exclude:'Женя'}};const out=s.client.resolveResultSetFollowUp('открой вторую',{chatSessionId:raw.chatSessionId,resultSet:raw.activeResultSet,resultItems:items,queryContext:comparison});assert.deepEqual(JSON.parse(JSON.stringify(out.queryContext)),comparison);count++;}
 {const s=setup([{ticket_id:'A',address:'Памятная 3'},{ticket_id:'B',address:'Памятная 30'}]),chat=s.make();await chat.send('list');await chat.send('открой вторую');await chat.send('Памятная');const saved=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));assert.equal(saved.selectedTicketId,null,'clarification cannot silently keep a previous selection');assert.equal(saved.activeResultSet.ticketIds.length,2);await chat.send('открой карточку');assert.ok(s.seen.at(-1).meta.clarification);assert.equal(s.calls(),1);count++;}
 for(const q of ['открой id 2','открой заявку id 2','открой вторую','открой номер 2 из списка']){
  const s=setup([{ticket_id:'2',address:'Адрес один'},{ticket_id:'other',address:'Адрес два'}]);await s.make().send('list');await s.make().send(q);
  assert.equal(s.seen.at(-1).presentation?.ticket_id,q.includes('id')?'2':'other',q);assert.equal(s.calls(),1,'explicit ID and position survive reload without backend');count++;
 }
 for(const alternative of ["Пам'ятна 13","Пам'ятна 3А"]){
  for(const q of ['открой Памятная 3','Открой память на три']){
   const s=setup([{ticket_id:'A',address:"Пам'ятна 3"},{ticket_id:'B',address:alternative}]),chat=s.make();await chat.send('list');const before=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));await chat.send(q);
   const out=s.seen.at(-1),saved=JSON.parse(s.storage.getItem('mtAiChatHistoryV1'));assert.ok(out.meta.clarification,q+alternative);assert.equal(out.presentation,null);assert.equal(out.meta.rounds,0);assert.equal(out.meta.toolCallsMade,0);assert.equal(s.calls(),1,'ambiguity never triggers broad/global search');assert.deepEqual(saved.activeResultSet,before.activeResultSet);assert.deepEqual(saved.activeResultItems,before.activeResultItems);assert.deepEqual(saved.messages.at(-1).queryContext,qc);count++;
   if(alternative.endsWith('3А')){await s.make().send('3А');assert.equal(s.seen.at(-1).presentation.ticket_id,'B');assert.equal(s.calls(),1,'house suffix resolves locally after clarification/reload');count++;}
  }
 }
 {const s=setup([{ticket_id:'2',address:'Адрес один'},{ticket_id:'other',address:'Адрес два'}]),chat=s.make();await chat.send('list');await chat.send('открой 2');assert.ok(s.seen.at(-1).meta.clarification,'bare number conflicting with ID must not guess');await chat.send('открой id missing');assert.ok(s.seen.at(-1).meta.clarification);assert.equal(s.calls(),1);count+=2;}
 console.log(`PASS resultSet-first ${count} regressions: bounded resolution, 0 backend/provider rounds, no 245 expansion, context/reload preserved`);
})().catch(e=>{console.error(e);process.exitCode=1;});
