'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const {createServer,createDevice}=require('./helpers/sync-gas-harness');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const serializer=source.slice(source.indexOf('function ticketToSyncPayload('),source.indexOf('function shiftToSyncPayload('));
const load=p=>import(pathToFileURL(path.join(root,'mcp/src',p)).href);
(async()=>{
 const {ticketFromGasRow,redactTicket,assertNoForbidden}=await load('gas/mappers.js');
 const {runSmartQuery}=await load('ask/smart-query.js');
 const server=createServer(),device=await createDevice({server,online:false});
 vm.runInContext(serializer,device.ctx);
 device.engine.payload=(entity,item)=>{assert.equal(entity,'ticket');return device.ctx.ticketToSyncPayload(item);};
 const original={id:'SYNTHETIC-ROUNDTRIP',date:'15.09.2026',time:'10:00',type:'Підключення',sum:100,content:'',macAddress:'001122334455',connectMasters:[{name:'Петя',letter:'П'},{name:'Женя',letter:'Ж'}],tags:['Петя','Женя']};
 const before=JSON.stringify(original);
 await device.addTicket(original);
 assert.equal(JSON.stringify(original),before,'serializer must not mutate local ticket');
 assert.equal(server.ticketIds().length,0,'offline write only queues the real payload');
 assert.deepEqual(JSON.parse(device.record('ticket',original.id).head.body.fullDataJson).connectMasters,original.connectMasters);
 device.setOnline(true);await device.flush();
 assert.equal(device.isSynced('ticket',original.id),true);
 const row=server.ticketRow(original.id),ticket=redactTicket(ticketFromGasRow(row));
 assert.equal(row.id,original.id);assert.equal(ticket.id,original.id);
 assert.deepEqual(ticket.connectMasters,['Петя','Женя']);assertNoForbidden(ticket);
 const ctx={tickets:[ticket],shifts:[],searchIndex:[]};
 const query={mode:'list',coworker:'Петей',semantic:{entity:'onu',action:'install',profile:'onu_physical'}};
 const data=runSmartQuery(ctx,query).data;
 assert.equal(data.matched,1);assert.equal(data.evidence[0].coworker_reason,'direct_ticket');
 assert.equal(data.evidence[0].events[0].reason,'derived_from_connection');
 assert.ok(!JSON.stringify(data.evidence).includes(original.macAddress));
 const requests=server.requests.length;await device.saveTickets();
 assert.equal(server.requests.length,requests,'unchanged ticket does not enqueue a backfill');
 await device.editTicket(original.id,{connectMasters:[]});
 assert.deepEqual(JSON.parse(server.ticketRow(original.id).fullDataJson).connectMasters,[],'explicit removal survives update, not stale previous masters');
 assert.equal(server.ticketSheet.rows[0].length,8,'no new Sheets columns');
 const legacy={id:'LEGACY',date:'15.09.2026',time:'10:00',type:'Підключення',content:'',tags:['Петя']};
 const oldPending=device.ctx.MTSyncEngineCore.enqueue({records:{}},{entity:'ticket',id:legacy.id,payload:{id:legacy.id,date:legacy.date,time:legacy.time,sum:0,tags:legacy.tags,fullDataJson:'{"type":"Підключення"}'}},()=> 'synthetic_request_abcdefghijkl');
 const restarted=await createDevice({server,online:false,tickets:[legacy],journal:oldPending});
 vm.runInContext(serializer,restarted.ctx);restarted.engine.payload=(_entity,item)=>restarted.ctx.ticketToSyncPayload(item);
 const journal=JSON.stringify(restarted.journal());await restarted.saveTickets();
 assert.equal(JSON.stringify(restarted.journal()),journal,'old pending payload and historical ticket untouched on startup/no-op save');
 assert.equal(Object.hasOwn(JSON.parse(restarted.record('ticket',legacy.id).head.body.fullDataJson),'connectMasters'),false);
 console.log('PASS real serializer -> durable offline journal -> signed transport -> real Code.gs existing JSON column -> mapper/redaction -> direct semantic coworker; no backfill/ID/schema change');
})().catch(e=>{console.error(e);process.exitCode=1;});
