'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','js','ticket-editor-domain.js'),'utf8');
const hasSource=source.slice(source.indexOf('function hasUnsavedChanges(){'),source.indexOf('/* ---- Автозбереження чернетки ---- */'));
const context={calcState:{},formTouchedByUser:false,feeIsAutoDefault:true,tariffIsAutoDefault:true,TYPE_TAG_MAP:{'Підключення':'connect'},MTToolsCore:{explicitCoordinates:()=>null}};
vm.createContext(context);vm.runInContext(hasSource,context);
const defaults=()=>({type:'Підключення',tags:['connect'],callFee:150,tariff:100,cables:[],equipment:[],presetWorks:[],additionalWork:[{desc:'',sum:0}]});
context.calcState=defaults();
assert.equal(context.hasUnsavedChanges(),false,'opening calculator with defaults is clean');
context.calcState={...defaults(),city:'Automatically supplied'};
assert.equal(context.hasUnsavedChanges(),false,'automatic/default initialization is clean');
context.formTouchedByUser=true;
assert.equal(context.hasUnsavedChanges(),true,'manual meaningful field change remains dirty');
context.formTouchedByUser=false;
context.calcState={...defaults(),id:'ticket-a',city:'Saved city',clientName:'Saved client'};
assert.equal(context.hasUnsavedChanges(),false,'opening existing ticket without interaction is clean');
context.formTouchedByUser=true;context.calcState.clientName='Changed client';
assert.equal(context.hasUnsavedChanges(),true,'manual edit of existing ticket remains dirty');
assert.match(source,/function loadTicketIntoForm[\s\S]*?fillFormFromState\(\);[\s\S]*?formTouchedByUser\s*=\s*false/,'loading a saved ticket remains clean after programmatic rendering');
assert.match(source,/restoreDraftIfAny[\s\S]*?loadTicketIntoForm\(draft\.state\);[\s\S]*?formTouchedByUser\s*=\s*true/,'restored unsaved draft remains dirty');
const bindings=fs.readFileSync(path.join(__dirname,'..','js','tickets-bindings.js'),'utf8');
assert.match(bindings,/\.mixed-item-toggle,\.photo-remove,\.aw-remove,\[data-calctag\],\[data-master-letter\],\[data-address-suggestion\][\s\S]*?formTouchedByUser\s*=\s*true/,'non-input calculator mutations still mark the form dirty');
assert.match(bindings,/document\.getElementById\('f_mac'\)\.value\s*=\s*mac;[\s\S]*?formTouchedByUser\s*=\s*true/,'scanner selection remains a user edit');
console.log('PASS calculator dirty state depends on meaningful user interaction, including existing-ticket and draft lifecycle');
