'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const core=require('../js/tools-core.js'),read=file=>fs.readFileSync(file,'utf8');
const result={online:true,summaryStatus:'ok',internetStatus:'ok',dnsStatus:'indirect',publicIp:'203.0.113.8',resources:[]};
const first=core.makeDiagnosticRecord(result,{id:'profile-1',address:'Дніпро',ticketId:'t1'},new Date('2026-09-07T08:00:00Z'));
const second=core.makeDiagnosticRecord({...result,summaryStatus:'warning',publicIp:''},{id:'profile-1',address:'Дніпро',ticketId:'t1'},new Date('2026-09-07T09:00:00Z'));
const initial=[];const once=core.appendDiagnosticHistory(initial,first),twice=core.appendDiagnosticHistory(once,second);
assert.equal(initial.length,0);assert.equal(once.length,1);assert.equal(twice.length,2);assert.equal(twice[1].summaryStatus,'warning');
assert.doesNotThrow(()=>core.sanitizeDiagnostics([null,{},first,{id:'bad',timestamp:'now',result:{resources:'bad'}}]));
const form=read('js/ticket-form-domain.js'),app=read('app.js'),security=read('js/security-runtime-v65-9.js'),ui=read('js/tickets-render.js'),domain=require('./helpers/tools-source').readToolsSource(),share=read('js/share-domain.js');
assert.match(form,/diagnosticHistory:\[\]/,'new and legacy-compatible tickets default to an empty history');
assert.match(app,/diagnosticHistory:typeof MTToolsCore[^\n]+sanitizeDiagnostics/,'ticket sync fullDataJson carries sanitized history');
assert.match(security,/sanitizeDiagnostics\(t\.diagnosticHistory\|\|\[\]\)\.slice\(-200\)/,'imported/restored history is bounded and sanitized');
assert.match(ui,/Історія діагностик/);assert.match(ui,/Діагностика ще не виконувалась/);
assert.match(domain,/async function toolsSaveCurrentDiagnostic/);assert.match(domain,/draft\.state\.diagnosticHistory=MTToolsCore\.appendDiagnosticHistory\(previousDraft,record\)/);assert.match(domain,/!ticket\|\|await saveTickets\(\)/,'saving history keeps the active draft and reuses canonical ticket persistence when one exists');
assert.doesNotMatch(domain,/toolsDiagnostics\.push\(record\)/,'new diagnostics are no longer written only to the legacy profile store');
assert.match(share,/Історія\\s\+діагностик/,'dispatcher sanitizer excludes diagnostic history labels');
assert.doesNotMatch(share,/JSON\.stringify\([^\n]*diagnosticHistory/,'dispatcher never serializes ticket history');
console.log('PASS append-only ticket diagnostic history, sync/restore compatibility, safe UI and dispatcher exclusion');
