'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../js/dispatcher-report-core.js');
const read=p=>fs.readFileSync(p,'utf8');
const ctx={globalThis:{},MTStorageRegistry:{key:()=> 'view'},localStorage:{getItem:()=>null,setItem(){}},escapeHtml:v=>String(v??'').replace(/</g,'&lt;'),fmtMoney:v=>Number(v||0)+' грн'};
ctx.globalThis=ctx;
vm.runInNewContext(read('js/tickets-compact-view.js'),ctx);
const other={id:'test-other',type:'Інше',date:'08.10.2026',time:'12:00',sum:0,otherNote:'Забрати ONU завтра',city:'SHOULD_NOT_DISPLAY',address:'SHOULD_NOT_DISPLAY',equipment:[{label:'ONU',qty:1}],diagnosticHistory:[{}],connectMasters:['PRIVATE_PARTNER']};
const before=JSON.stringify(other),compact=ctx.MTTicketCompactView.renderCard(other);
assert(compact.includes('Забрати ONU завтра'));
for(const s of ['SHOULD_NOT_DISPLAY','Адресу не вказано','tc-status-row','Telegram','Таблиця'])assert(!compact.includes(s));
vm.runInNewContext(read('js/tickets-render.js'),ctx);
const expanded=ctx.renderTicketCard(other);
for(const s of ['Забрати ONU завтра','Редагувати','Переслати','Видалити','0 грн'])assert(expanded.includes(s));
for(const s of ['SHOULD_NOT_DISPLAY','діагности','Напарник','Матеріали','PRIVATE_PARTNER','В профіль','Google Maps'])assert(!expanded.includes(s));
assert.equal(JSON.stringify(other),before);
const materials=ctx.ticketMaterialPresentation({equipment:[{label:'ONU',qty:0},{label:'Роутер',qty:1},{label:'Кріплення',qty:4}],cables:[{label:'UTP',meters:37},{label:'Оптика',meters:0}]},'🛠️ ONU: 1 шт. х 0 грн\n🛠️ Роутер: 1 шт. х 100 грн\n🔌 UTP: 37м\nАдреса: Будинок 0');
assert(!materials.html.includes('ONU'));assert(!materials.html.includes('Оптика'));
for(const s of ['Роутер — 1 шт.','Кріплення — 4 шт.','UTP — 37 м'])assert(materials.html.includes(s));
assert.equal(materials.content,'Адреса: Будинок 0');
(async()=>{
  const {buildDTO}=await import('../js/dispatcher-report-projection.mjs');
  const dto=await buildDTO({...other,payment:'Готівка'},core);
  for(const key of ['city','address_display','materials_display','partner_display','mac_onu'])assert.equal(dto[key],'');
  assert.equal(dto.dispatcher_comment,other.otherNote);assert.equal(dto.onu_used,0);assert.equal(JSON.stringify(other),before);
  const ticket={...other,id:'test-normal',type:'Ремонт',otherNote:'',note:'Виконано',payment:'Готівка',sum:100,equipment:[{label:'ONU',qty:0},{label:'Роутер',qty:1}],cables:[{label:'UTP',meters:37},{label:'Оптика',meters:0}]};
  const projected=await buildDTO(ticket,core);
  assert.equal(projected.materials_display,'Роутер — 1 шт.\nUTP — 37 м');
  const text=core.render([projected]).blocks.find(b=>b.kind==='ticket').text;
  assert(!text.includes('ONU: 0'));assert(!text.includes('Роутер: 0'));assert(text.includes('Роутер — 1 шт.\nUTP — 37 м'));
  for(const file of ['js/finance-utils.js','js/sync-contract.js'])assert(!read(file).includes('MT_REPORT_VERIFIED'));
  console.log('PASS v91.90 compact/other/materials/privacy/zero projection and unchanged persisted inputs');
})().catch(e=>{console.error(e);process.exitCode=1;});
