'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),storageSource=fs.readFileSync(path.join(root,'js','offline-map-storage.js'),'utf8'),tools=fs.readFileSync(path.join(root,'js','tools-domain.js'),'utf8');
const values=new Map([['mtOfflineMapModeV1','auto']]);
const context={module:{exports:{}},exports:{},console,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},navigator:{storage:{}},pmtiles:{}};
context.globalThis=context;vm.createContext(context);vm.runInContext(storageSource,context);
const api=context.module.exports;
assert.equal(api.getMode(),'auto','persistent mode initially auto');
api.setViewMode('offline');
assert.equal(api.getMode(),'offline','manual Offline affects current view');
assert.equal(values.get('mtOfflineMapModeV1'),'auto','manual Offline does not replace persistent Auto');
api.resetViewMode();
assert.equal(api.getMode(),'auto','close/reopen returns to Auto');
const resolved=online=>api.getMode()==='auto'?(online?'online':'offline'):api.getMode();
assert.equal(resolved(true),'online','Auto chooses online while connected');
assert.equal(resolved(false),'offline','Auto chooses installed offline map without connectivity');
api.setMode('online');assert.equal(api.getMode(),'online','explicit manual Online still works');
api.setMode('auto');api.setViewMode('offline');api.resetViewMode();assert.equal(api.getMode(),'auto');
assert.match(tools,/function toolsOpenOfflineMap\(\)\{MTOfflineMap\.setViewMode\('offline'\);toolsNavigate\('map'\);\}/);
assert.match(tools,/toolsOpenRootFromTab[\s\S]*?MTOfflineMap\?\.resetViewMode\?\.\(\)/,'reopening tools clears view override');
assert.match(tools,/if\(event\.target\.id==='toolsMapBaseMode'\)[\s\S]*?setViewMode\('offline'\)[\s\S]*?setMode\(event\.target\.value\)/,'selector keeps Offline temporary and Auto/Online explicit');
assert.match(tools,/window\.addEventListener\('online',[\s\S]*?MTOfflineMap\.getMode\(\)==='auto'/);
assert.match(tools,/window\.addEventListener\('offline',[\s\S]*?MTOfflineMap\.getMode\(\)==='auto'/);
values.set('mtOfflineMapModeV1','offline');api.resetViewMode();
assert.equal(values.get('mtOfflineMapModeV1'),'auto','legacy sticky Offline is normalized on reopen without touching map data');
console.log('PASS Offline is a view-only override; Auto/Online persistence and connectivity behavior remain intact');
