'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8'),source=read('js/tools-domain.js'),coreSource=read('js/tools-core.js'),adapter=read('js/tools-map-maplibre.js'),styles=read('styles.css');
assert.match(source,/Вибрати файл \.pmtiles і встановити/);
assert.match(source,/✅ Офлайн-карта встановлена/);
assert.match(source,/Технічна інформація/);
const areaUi=source.match(/function toolsOfflineAreasHtml[\s\S]*?\n}\nfunction toolsOfflineHtml/)?.[0]||'';
assert.ok(areaUi.indexOf('Карта не встановлена')<areaUi.indexOf('BBox:'),'technical BBox stays below the collapsible technical summary');
assert.doesNotMatch(areaUi,/CLI|MVT|daily build/,'primary saved-area flow has no extraction jargon');
assert.match(source,/MTOfflineMap\.inspectFile\(file\)/);
assert.match(source,/MTOfflineMap\.quotaFor\(file\.size\)/);
assert.match(source,/MTOfflineMap\.install\(file,info,\{areaId:/);
assert.match(source,/Видалити лише офлайн-карту\?/);
assert.match(source,/Попередню карту не змінено/,'failed replacement explicitly preserves the installed map');
assert.match(source,/PMTILES_TILE_TYPE_UNSUPPORTED/);
assert.match(source,/Схожа область вже існує[\s\S]*Замінити існуючу[\s\S]*Зберегти як нову[\s\S]*Скасувати/);
assert.match(styles,/\.tools-offline-install\{[^}]*min-height:46px/);
assert.match(adapter,/OBJECT_ICON_SCALE=\{min:\.78,max:1\.35\}/,'object markers have readable Leaflet-parity scaling');
assert.match(adapter,/markerElement\('Моє місце',true\)/,'GPS remains a separate configurable DOM marker');
assert.ok(48/2*1.35<40,'largest rendered object pin stays smaller than the default 40px GPS pin');
assert.match(source,/function toolsOpenOfflineMap\(\)\{MTOfflineMap\.setViewMode\('offline'\);toolsNavigate\('map'\);\}/,'Open activates the installed map without persisting Offline as the default');
const context={module:{exports:{}},exports:{},console,Date,Math};vm.runInNewContext(coreSource,context);const core=context.module.exports;
const first={name:'Дніпро',minLat:48,minLng:34,maxLat:49,maxLng:36};
assert.equal(core.offlineAreaDuplicate(first,{...first,name:'дніпро'}),true,'same normalized name warns');
assert.equal(core.offlineAreaDuplicate(first,{name:'Інша',minLat:48.01,minLng:34.01,maxLat:48.99,maxLng:35.99}),true,'nearly identical bounds warn');
assert.equal(core.offlineAreaDuplicate(first,{name:'Львів',minLat:49,minLng:23,maxLat:50,maxLng:25}),false);
console.log('PASS simplified offline install/status/replace UX, duplicate warning and larger MapLibre markers');
