'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'sw.js'),'utf8'),handlers={},deleted=[],added=[];let localTouches=0,idbTouches=0;
assert.match(source,/CACHE_NAME\s*=\s*'maister-treker-v66-runtime-32'/,'installed-PWA cache revision includes the v90 repair fee fix');
assert.match(fs.readFileSync(path.join(root,'app.js'),'utf8'),/APP_VERSION\s*=\s*'v90 · 2026-09-05'/,'canonical release identity is v90');
assert.match(fs.readFileSync(path.join(root,'js','security-audit-fixes-v65-18-9.js'),'utf8'),/SECURITY_AUDIT_RELEASE_LABEL\s*=\s*'v90 · 2026-09-05'/,'final compatibility wrapper displays canonical v90 identity');
const cache={addAll:async assets=>added.push(...assets),match:async()=>null,put:async()=>{}};
const context={URL,fetch:async()=>({ok:true,clone(){return this;}}),caches:{open:async()=>cache,keys:async()=>['maister-treker-v65-old','unrelated-cache'],delete:async key=>{deleted.push(key);return true;},match:async()=>null},clients:{matchAll:async()=>[],claim:async()=>{}},self:{addEventListener:(name,fn)=>{handlers[name]=fn;},skipWaiting:()=>{}},localStorage:new Proxy({},{get(){localTouches++;}}),indexedDB:new Proxy({},{get(){idbTouches++;}})};context.self.clients=context.clients;vm.createContext(context);vm.runInContext(source,context);
async function fire(name){let promise;handlers[name]({waitUntil:p=>{promise=p;}});await promise;}
(async()=>{await fire('install');await fire('activate');assert.ok(added.includes('./index.html'));assert.ok(added.includes('./d.js'));assert.ok(deleted.includes('maister-treker-v65-old'));assert.equal(localTouches,0);assert.equal(idbTouches,0);assert.equal(/\.navigate\s*\(/.test(source),false);assert.equal(/indexedDB|localStorage/.test(source),false);for(const asset of added){if(!asset.startsWith('./')||asset==='./')continue;assert.equal(fs.existsSync(path.join(root,asset.slice(2))),true,`missing cached asset ${asset}`);}const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/<script src="([^"]+)"/g))assert.equal(fs.existsSync(path.join(root,match[1])),true,`missing bootstrap script ${match[1]}`);console.log('PASS SW v65-cache to v66 activation preserves application data APIs and assets resolve');})().catch(e=>{console.error(e);process.exitCode=1;});
