'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'sw.js'),'utf8'),appSource=fs.readFileSync(path.join(root,'app.js'),'utf8'),handlers={},deleted=[],added=[];let localTouches=0,idbTouches=0;
assert.match(source,/CACHE_NAME\s*=\s*'maister-treker-v66-runtime-42'/,'installed-PWA cache revision is unique for v91.5');
assert.match(appSource,/APP_VERSION\s*=\s*'v91\.5 · 2026-09-06'/,'canonical release identity is v91.5');
assert.match(appSource,/register\('sw\.js',\{updateViaCache:'none'\}\)/,'browser cache cannot suppress the service-worker update check');
assert.match(appSource,/addEventListener\('controllerchange',[\s\S]*window\.location\.reload\(\)/,'new controller activates the fresh application shell without clearing site data');
assert.match(fs.readFileSync(path.join(root,'js','security-audit-fixes-v65-18-9.js'),'utf8'),/SECURITY_AUDIT_RELEASE_LABEL\s*=\s*'v91\.5 · 2026-09-06'/,'final compatibility wrapper displays canonical v91.5 identity');
const cache={addAll:async assets=>added.push(...assets),match:async()=>null,put:async()=>{}};
const context={URL,Request:class Request{constructor(url,options){this.url=url;this.cache=options&&options.cache;}},fetch:async()=>({ok:true,status:200,clone(){return this;}}),caches:{open:async()=>cache,keys:async()=>['maister-treker-v66-runtime-41','unrelated-cache'],delete:async key=>{deleted.push(key);return true;},match:async()=>null},clients:{matchAll:async()=>[],claim:async()=>{}},self:{addEventListener:(name,fn)=>{handlers[name]=fn;},skipWaiting:()=>{}},localStorage:new Proxy({},{get(){localTouches++;}}),indexedDB:new Proxy({},{get(){idbTouches++;}})};context.self.clients=context.clients;vm.createContext(context);vm.runInContext(source,context);
async function fire(name){let promise;handlers[name]({waitUntil:p=>{promise=p;}});await promise;}
(async()=>{await fire('install');await fire('activate');assert.ok(added.some(item=>item.url==='./index.html'&&item.cache==='reload'));assert.ok(added.some(item=>item.url==='./d.js'&&item.cache==='reload'));assert.ok(deleted.includes('maister-treker-v66-runtime-41'));assert.ok(source.includes("if(/\\.(?:js|mjs|css)$/.test(url.pathname))"),'production code assets have a dedicated refresh path');assert.ok(source.includes("fetch(e.request,{cache:'no-store'})"),'production code assets use network-first refresh');assert.equal(localTouches,0);assert.equal(idbTouches,0);assert.equal(/Clear-Site-Data|indexedDB|localStorage/.test(source),false);assert.equal(/Clear-Site-Data|deleteDatabase/.test(appSource),false);for(const asset of added){const value=asset.url;if(!value.startsWith('./')||value==='./')continue;assert.equal(fs.existsSync(path.join(root,value.slice(2))),true,`missing cached asset ${value}`);}const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/<script src="([^"]+)"/g))assert.equal(fs.existsSync(path.join(root,match[1])),true,`missing bootstrap script ${match[1]}`);console.log('PASS SW v91.5 refreshes production code, preserves offline shell and never clears application data');})().catch(e=>{console.error(e);process.exitCode=1;});
