'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const map=read('js/tools-map.js'),domain=read('js/tools-domain.js'),styles=read('styles.css'),address=read('js/address-render.js'),addressDomain=read('js/ticket-address-domain.js'),telegram=read('js/photo-telegram-domain.js');
const core=require('../js/tools-core.js');

assert.match(styles,/\.modal-overlay\{[\s\S]*?z-index:2000/,'1 form bottom-sheet stays above all Leaflet panes');
assert.match(styles,/\.tools-point-editor-overlay\{[^}]*pointer-events:none/);assert.match(styles,/\.tools-point-editor-overlay \.modal\{[^}]*pointer-events:auto/,'map remains draggable outside the point editor sheet');
assert.match(styles,/\.tools-map-editor-open\{padding-bottom:64vh/);assert.match(domain,/classList\.add\('tools-map-editor-open'\)/,'point editor creates enough scroll room to keep the map visible');
assert.match(map,/startPointPlacement[\s\S]*map\.on\('click',clickHandler\)/,'2 add mode waits for a map tap');
assert.match(map,/map\.panTo\(\[point\.lat,point\.lng\]/);assert.match(map,/scrollIntoView\(\{block:'start'\}\)/,'placed marker is kept in the visible map area above the sheet');
assert.match(map,/title:'Новий об’єкт'\}\)\.addTo\(layer\)/);assert.match(map,/draggable:true/,'3 temporary marker is draggable');
assert.ok(domain.indexOf('toolsSaveNetworkPoints()')<domain.indexOf('if(isNew)await toolsSendNetworkPointTelegram'),'4 object is stored locally before automatic new-object transport');
assert.match(map,/userLayer=root\.L\.layerGroup/);assert.match(map,/const layer=root\.L\.layerGroup\(\)\.addTo\(map\)/,'5 GPS and working marker use separate layers');
assert.match(domain,/abonent-back-map-btn/);assert.match(address,/toolsMapReturnButtonHtml/);assert.match(addressDomain,/toolsReturnFromProfileToMap/,'6 profile has a direct return to map');
assert.match(map,/savedView=\{lat:center\.lat,lng:center\.lng,zoom:map\.getZoom\(\)\}/);assert.match(map,/const selected=new Set\(categories\)/,'7 viewport and filters remain in map runtime');
assert.match(domain,/toolsSendNetworkPointTelegram[\s\S]*sendToTelegramChat\(chatId,text/,'8 network point reuses existing Telegram transport');
assert.match(domain,/Точку збережено локально[\s\S]*if\(isNew\)await toolsSendNetworkPointTelegram/,'9 Telegram failure cannot remove the locally saved point');
assert.match(domain,/toolsPointPhotoPreview/);assert.match(domain,/resolvePhotoAsync/,'10 saved point photos can be opened later');
assert.doesNotMatch(domain,/\['IPv6',r\.ipv6/);assert.doesNotMatch(domain,/result\.ipFamily\|\|''/,'11 IPv6 is hidden from results and profile history');
assert.match(domain,/Перевірити швидкість/);assert.match(domain,/speed\.cloudflare\.com/);assert.doesNotMatch(domain,/rows\.push\(\['Download'/,'12 speed UX has no fake empty metrics');
assert.match(domain,/Офлайн-підкладка для цієї області не встановлена/);assert.match(domain,/toolsMapEmptyState/,'13 missing basemap has an honest empty state');
assert.match(domain,/Збережена лише область/);assert.match(domain,/Офлайн-карта встановлена/,'14 multiple areas expose honest installation status');
assert.match(map,/function addOnlineBaseLayer/);assert.match(map,/tile\.openstreetmap\.org/,'15 online map path remains intact');
assert.match(domain,/Зберегти межі області \(\.json\)/);assert.match(domain,/Це лише межі та масштаб, не файл карти/,'area JSON is explicitly not presented as map data');
assert.match(telegram,/photoResult\.ok/,'photo send failures are reported by the existing transport');
const sourcePoints=[{id:'point-a',type:'FOB'},{id:'point-b',type:'Муфта'}],tickets=[{id:'ticket-1',city:'Київ'}],profiles=[{id:'profile-1'}];
const removed=core.removeNetworkPoint(sourcePoints,'point-a');
assert.equal(removed.removed.id,'point-a');assert.deepEqual(removed.points.map(point=>point.id),['point-b'],'only the selected network point is removed');
assert.equal(sourcePoints.length,2);assert.equal(tickets.length,1);assert.equal(profiles.length,1,'ticket and address profile collections stay untouched');
assert.match(domain,/Видалити цей об’єкт\?/);assert.match(domain,/>Видалити<\/button>/);assert.match(domain,/>Скасувати<\/button>/,'delete requires explicit confirmation or cancellation');
assert.match(domain,/toolsPointDeleteCancelBtn'\)\.onclick=\(\)=>toolsShowNetworkPoint/,'cancel returns to the point card without deleting');
assert.match(domain,/toolsSaveNetworkPoints\(\)[\s\S]*deletePhotoKey\(key\)/,'point storage is updated before related local photos are deleted');
assert.match(domain,/closeModal\(\);renderToolsScreen\(toolsView\)/,'active list or map rerenders immediately after deletion');
assert.match(domain,/toolsPhotoKeyStillUsed/);assert.match(domain,/inTicket=tickets\.some/,'shared ticket photos are not deleted');
console.log('PASS field map placement, return navigation, Telegram, diagnostics and honest offline UX');
