'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const core=require('../js/tools-core.js'),domain=fs.readFileSync(path.join(__dirname,'..','js','tools-domain.js'),'utf8');
const point={id:'fob-03',type:'FOB',name:'FOB-03',label:'Шафа 3',city:'Таромське',street:'вул. Генерала Волівача',house:'12',note:'біля білого паркану',lat:48.123456,lng:37.654321,photoKeys:['idb:p1']};
const preview=core.networkPointPreviewData(point);
assert.deepEqual(preview,{id:'fob-03',type:'FOB',name:'FOB-03',label:'Шафа 3',address:'Таромське, вул. Генерала Волівача, 12',city:'Таромське',street:'вул. Генерала Волівача',house:'12',note:'біля білого паркану',coordinates:'48.123456, 37.654321',photoKeys:['idb:p1']});
const empty=core.networkPointPreviewData({id:'node-1',type:'Вузол',lat:48,lng:37});
assert.equal(empty.note,'');assert.equal(empty.name,'');assert.deepEqual(empty.photoKeys,[]);
assert.equal(core.networkPointPickerMeta({...point,name:'FOB-03'}),'«біля білого паркану» · FOB-03');
assert.notEqual(core.networkPointPickerMeta({...point,id:'fob-04',name:'FOB-04'}),core.networkPointPickerMeta(point));
const htmlSource=domain.slice(domain.indexOf('function toolsTicketNetworkPointPreviewHtml'),domain.indexOf('async function toolsPopulateTicketNetworkPointPreviewPhotos'));
const htmlContext={MTToolsCore:core,escapeHtml:value=>String(value??'').replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])};vm.createContext(htmlContext);vm.runInContext(htmlSource,htmlContext);
const previewHtml=htmlContext.toolsTicketNetworkPointPreviewHtml(point);
for(const value of ['FOB','FOB-03','fob-03','Таромське, вул. Генерала Волівача, 12','біля білого паркану','48.123456, 37.654321'])assert.match(previewHtml,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
const emptyHtml=htmlContext.toolsTicketNetworkPointPreviewHtml({id:'node-1',type:'Вузол',lat:48,lng:37});
assert.doesNotMatch(emptyHtml,/undefined|null|Примітка<\/span>/);assert.match(emptyHtml,/Фото недоступне/);
assert.match(domain,/ticket-network-preview/);assert.match(domain,/aria-label="Переглянути деталі/);
assert.match(domain,/function toolsOpenTicketNetworkPointPreview/);
assert.match(domain,/id="ticketNetworkPointPreviewMapBtn"[\s\S]*id="ticketNetworkPointPreviewLinkBtn"[\s\S]*id="ticketNetworkPointPreviewCloseBtn"/);
assert.match(domain,/ticketNetworkPointPreviewLinkBtn'[\s\S]*toolsLinkNetworkPointToTicket\(point\.id\)/);
assert.match(domain,/ticketNetworkPointPreviewMapBtn'[\s\S]*toolsShowNetworkPointOnMap\(point\)/);
const previewBody=domain.slice(domain.indexOf('function toolsOpenTicketNetworkPointPreview'),domain.indexOf('function toolsNetworkPointPhotoSignature'));
assert.doesNotMatch(previewBody,/toolsSaveNetworkPoints|toolsOpenNetworkPointEditor|toolsDeleteNetworkPoint/);
console.log('PASS read-only network-point preview reuses link, map and photo lifecycles');
