'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','js','photo-telegram-domain.js'),'utf8'),reliability=fs.readFileSync(path.join(__dirname,'..','js','telegram-backup-reliability-v65-13.js'),'utf8');
const response=data=>({status:200,headers:{get:()=>null},json:async()=>data});
function harness({deleteFails=false,ambiguousDocument=false}={}){const ticket={id:'uuid-a',type:'Ремонт',content:'new text',photos:['idb:p1'],tgBackedUp:true,tgBackupPending:true,tgSepMsgId:11,tgTextMsgId:12,tgPhotoMsgId:13,tgPhotoMsgIds:[13],tgPhotoFileId:'file13',tgPhotoFileIds:['file13'],tgPhotoKeys:['idb:p1'],tgJsonMsgId:14},calls=[],deleted=[];let next=100;
 const context={AbortController,Blob,FormData,clearTimeout,setTimeout,console:{error(){}},navigator:{onLine:true},settings:{tgBotToken:'token',tgBackupChatId:'chat'},tickets:[ticket],refreshTicketCardDom(){},saveTicketsLocalOnly:async()=>true,resolvePhotoAsync:async()=>null,fetch:async(url,opts)=>{calls.push(String(url));if(/deleteMessage$/.test(String(url))){const id=JSON.parse(opts.body).message_id;if(!deleteFails)deleted.push(id);return response({ok:!deleteFails,description:deleteFails?'temporary delete failure':''});}throw new Error('unexpected direct fetch');}};
 vm.createContext(context);vm.runInContext(source,context);context.fetchWithRetry=async(url,opts)=>{calls.push(String(url));const endpoint=String(url).split('/').pop();if(endpoint==='editMessageText')return response({ok:true,result:{message_id:JSON.parse(opts.body).message_id}});if(endpoint==='sendDocument'&&ambiguousDocument)throw Object.assign(new Error('response lost'),{telegramAmbiguous:true});return response({ok:true,result:{message_id:++next}});};return{context,ticket,calls,deleted};}
(async()=>{const normal=harness();assert.equal(await normal.context.backupTicketToTelegramNow(normal.ticket),true);assert.equal(normal.calls.filter(url=>/sendMessage|sendPhoto/.test(url)).length,0,'text edits and unchanged photos create no new messages');assert.equal(normal.calls.filter(url=>/sendDocument/.test(url)).length,1);assert.deepEqual(normal.deleted,[14],'only replaced JSON is deleted');assert.deepEqual(normal.ticket.tgPhotoMsgIds,[13]);
 const cleanup=harness({deleteFails:true});assert.equal(await cleanup.context.backupTicketToTelegramNow(cleanup.ticket),true);assert.equal(JSON.stringify(cleanup.ticket.tgBackupCleanupMsgIds),'[14]');assert.equal(cleanup.ticket.tgBackupPending,true);const sends=cleanup.calls.filter(url=>/send(?:Message|Photo|Document)/.test(url)).length;cleanup.context.fetch=async(url,opts)=>{cleanup.calls.push(String(url));cleanup.deleted.push(JSON.parse(opts.body).message_id);return response({ok:true});};assert.equal(await cleanup.context.backupTicketToTelegramNow(cleanup.ticket),true);assert.equal(cleanup.calls.filter(url=>/send(?:Message|Photo|Document)/.test(url)).length,sends,'cleanup retry never clones backup');
 const ambiguous=harness({ambiguousDocument:true});assert.equal(await ambiguous.context.backupTicketToTelegramNow(ambiguous.ticket),false);assert.equal(ambiguous.ticket.tgBackupAmbiguous,true);assert.equal(ambiguous.ticket.tgBackupPending,false);const before=ambiguous.calls.length;assert.equal(await ambiguous.context.backupTicketToTelegram(ambiguous.ticket,{pendingOnly:true}),false);assert.equal(ambiguous.calls.length,before,'ambiguous non-idempotent delivery is not blindly retried');assert.equal(ambiguous.context.tickets.length,1,'other ticket collections are untouched');assert.doesNotMatch(reliability,/for\(let attempt=1; attempt<=3/,'legacy sendPhoto blind retry is retired');console.log('PASS Telegram backup reuses logical card, retries cleanup only and parks ambiguous delivery without duplicates');})().catch(error=>{console.error(error);process.exitCode=1;});
