'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const domain=require('./helpers/tools-source').readToolsSource();
const map=fs.readFileSync(path.join(__dirname,'..','js','tools-map-maplibre.js'),'utf8');
assert.match(domain,/mountPicker\([^\n]+\{engine:'maplibre',initial/,'ticket picker explicitly requests shared MapLibre adapter');
for(const label of ['🗺️ Карта','🛰️ Супутник','📦 Офлайн'])assert.ok(map.includes(label),`picker exposes ${label}`);
assert.match(map,/data-mt-picker-base/);
assert.match(map,/if\(root\.navigator\?\.onLine===false\|\|!key\)/,'satellite safely falls back without BYOK or network');
assert.match(map,/catch\(error\)\{root\.MTSafeError\?\.[\s\S]*?picker\.map\.setStyle\(createOsmStyle\(\)\)/,'missing offline archive keeps picker usable and reports safely');
assert.match(domain,/const draft=MTToolsCore\.createGeoDraft\(calcState\)/);
assert.match(domain,/draft\.commit\(\)/);
assert.match(domain,/ticketGeoPointCancel'\)\.onclick=closePicker/,'cancel closes without commit');
console.log('PASS ticket geo picker reuses MapLibre layers with draft-only save semantics and safe fallbacks');
