'use strict';
const assert=require('node:assert/strict'),core=require('../js/tools-core.js');
function harness({downMbps,upMbps,latency=20,warmupMbps=null,outlierMbps=null,actualRatio=1,failUpload=false,timeoutDownload=false,cancelController=null}){let now=0,positiveGets=0;const calls=[];return{now:()=>now,calls,fetch:async(url,options={})=>{const method=options.method||'GET',requested=options.body?.byteLength||Number(new URL(url).searchParams.get('bytes'))||0;calls.push({method,requested,cache:options.cache,url});if(method==='POST'&&failUpload)throw Object.assign(new Error('upload unavailable'),{name:'NetworkError'});if(method==='GET'&&requested>250000&&timeoutDownload)throw Object.assign(new Error('timed out'),{name:'AbortError'});let actual=method==='POST'?0:Math.round(requested*actualRatio),speed=method==='POST'?upMbps:downMbps;if(method==='GET'&&requested>0){positiveGets++;if(positiveGets===1&&warmupMbps)speed=warmupMbps;else if(positiveGets===3&&outlierMbps)speed=outlierMbps;}now+=requested===0?latency:Math.max(1,(requested*8)/(speed*1000));if(cancelController&&positiveGets===1)cancelController.abort();return{ok:true,status:200,arrayBuffer:async()=>new ArrayBuffer(actual)};}};}
async function measure(config){const h=harness(config),result=await core.runBrowserSpeedTest({fetch:h.fetch,now:h.now,signal:config.cancelController?.signal,totalTimeoutMs:20000,requestTimeoutMs:1000});return{h,result};}
(async()=>{
  for(const [speed,tolerance] of [[8,1],[80,4],[700,35]]){const {result}=await measure({downMbps:speed,upMbps:speed/2});assert.ok(Math.abs(result.downloadMbps-speed)<=tolerance,`adaptive download represents ${speed} Mbps`);assert.ok(Math.abs(result.uploadMbps-speed/2)<=tolerance);}
  const fast=await measure({downMbps:700,upMbps:300,warmupMbps:180,outlierMbps:90});assert.ok(fast.result.downloadMbps>600,'warm-up and one slow outlier do not cap a fast line');assert.ok(fast.h.calls.filter(c=>c.method==='GET'&&c.requested>=15000000).length>=2,'fast line ramps to multi-sample large chunks');
  const partial=await measure({downMbps:100,upMbps:20,failUpload:true});assert.equal(partial.result.speedStatus,'partial');assert.equal(partial.result.uploadMbps,null);assert.ok(partial.result.downloadMbps>0);
  const timedOut=await measure({downMbps:100,upMbps:20,timeoutDownload:true});assert.equal(timedOut.result.speedStatus,'partial');assert.equal(timedOut.result.downloadMbps,null);assert.ok(timedOut.result.uploadMbps>0,'a timed-out direction stays unavailable instead of producing a fake number');
  const wrong=await measure({downMbps:100,upMbps:50,actualRatio:.5});assert.ok(wrong.result.downloadMbps>=49&&wrong.result.downloadMbps<=51,'download uses actual response byteLength, not requested bytes');
  const controller=new AbortController(),cancelled=await measure({downMbps:100,upMbps:50,cancelController:controller});assert.equal(cancelled.result.speedStatus,'cancelled');
  for(const call of fast.h.calls){assert.equal(call.cache,'no-store');assert.match(call.url,/_=/);}assert.match(fast.result.speedMethod,/parallel browser estimate v3/);assert.ok(fast.h.calls.reduce((sum,c)=>sum+c.requested,0)<=236000000,'traffic stays bounded');
  assert.ok(fast.h.calls.some((call,index,calls)=>call.requested>=10000000&&calls[index+1]?.requested===call.requested),'fast connections use concurrent equal-size streams');
  console.log('PASS Cloudflare parallel adaptive speed estimate, actual bytes, partial/cancel/outlier handling');
})().catch(error=>{console.error(error);process.exitCode=1;});
