'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),core=require('../js/tools-core.js');
const html=read('index.html'),styles=read('styles.css'),domain=read('js/tools-domain.js'),settingsSource=read('js/settings-core.js'),settingsRender=read('js/settings-render.js'),settingsDomain=read('js/settings-domain.js'),mapSource=read('js/tools-map.js'),mapLibreSource=read('js/tools-map-maplibre.js'),editor=read('js/ticket-editor-domain.js'),calculator=read('js/calculator-render.js'),share=read('js/share-domain.js'),backup=read('js/backup-system.js');

(async()=>{
  const mapModule=await import(`../js/tools-map-maplibre.js?v919=${Date.now()}`);assert.equal(mapModule.navigationControlOptions({matchMedia:()=>({matches:true})}).showZoom,false);assert.equal(mapModule.navigationControlOptions({matchMedia:()=>({matches:false})}).showZoom,true);assert.equal(mapModule.navigationControlOptions({matchMedia:()=>({matches:true})}).showCompass,true);
  const context={loadJSON:()=>null,localStorage:{setItem(){}},MTSingleWriterLock:undefined};vm.createContext(context);vm.runInContext(`${settingsSource};globalThis.normalize=normalizeMapMarkerPreferences`,context);
  const legacy=context.normalize(null,'large');assert.equal(legacy.private.size,'large');assert.equal(legacy.FOB.shape,'drop');
  const prefs=context.normalize({private:{shape:'badge',size:'small'},FOB:{shape:'pin',size:'large'},'Муфта':{shape:'broken',size:'huge'}},'classic');
  assert.deepEqual({...prefs.private},{shape:'badge',size:'small'});assert.deepEqual({...prefs.FOB},{shape:'pin',size:'large'});assert.deepEqual({...prefs['Муфта']},{shape:'drop',size:'medium'});
  prefs.private.size='large';assert.equal(prefs.private.shape,'badge');assert.equal(prefs.FOB.size,'large');assert.equal(prefs.FOB.shape,'pin','per-category shape and size remain independent');
  assert.match(settingsRender,/map-marker-preview shape-\$\{shape\}/);for(const shape of ['drop','pin','badge','contrast'])assert.ok(settingsRender.includes(`['${shape}'`)||settingsRender.includes(`,'${shape}'`),`${shape} visual choice exists`);
  assert.match(settingsDomain,/button\.dataset\.markerShape/);assert.match(settingsDomain,/button\.dataset\.markerSize/);assert.match(mapSource,/options\.markerPreferences/);assert.match(mapLibreSource,/options\.markerPreferences/);assert.match(mapLibreSource,/markerScale/);assert.match(styles,/shape-badge/);assert.match(styles,/shape-contrast/);
  assert.match(mapLibreSource,/navigationControlOptions\(root\)/);assert.match(mapLibreSource,/touchZoomRotate:true/);assert.match(styles,/@media \(max-width:430px\)[\s\S]*maplibregl-ctrl-zoom-in/,'mobile hides only visual +/- controls');
  assert.equal((domain.match(/class="tools-map-floating-btn" data-tools-action="map-my-location"/g)||[]).length,1);assert.equal((domain.match(/class="tools-map-floating-btn" data-tools-action="map-toggle-fullscreen"/g)||[]).length,1);assert.equal((mapLibreSource.match(/addBaseSwitcher\(\)/g)||[]).length,1,'one mount call for the single basemap switch');assert.doesNotMatch(mapLibreSource,/new gl\.FullscreenControl/);

  assert.match(html,/name="mt-f-a"[^>]+autocomplete="one-time-code"/);assert.match(html,/name="mt-f-b"[^>]+autocomplete="one-time-code"/);for(const id of ['f_city','f_street','f_house','f_apartment']){const tag=html.match(new RegExp(`<input[^>]+id="${id}"[^>]*>`))?.[0]||'';assert.doesNotMatch(tag,/name="[^"]*(?:city|street|address|location)/i,'ticket address inputs do not advertise postal field names');}
  assert.match(domain,/toolsCalculatorDraft=\{state:JSON\.parse\(JSON\.stringify\(calcState\)\)/);assert.match(domain,/toolsSuspendTicketAddressInputs\(\)/);assert.match(domain,/input\.value='';input\.disabled=true/);assert.match(domain,/toolsResumeTicketAddressInputs/,'hidden populated address cluster is removed only during diagnostics navigation');
  assert.match(calculator,/function renderCalcDiagnosticsStatus/);assert.match(editor,/renderCalcDiagnosticsStatus\(\)/);assert.match(html,/id="calcDiagnosticsStatus"/);
  const none=core.diagnosticStatus([]);assert.equal(none.status,'none');
  const ok=core.makeDiagnosticRecord({online:true,summaryStatus:'ok',resources:[]},{id:'p'},new Date('2026-09-07T10:00:00Z')),warning=core.makeDiagnosticRecord({online:true,summaryStatus:'warning',resources:[]},{id:'p'},new Date('2026-09-07T11:00:00Z'));
  assert.deepEqual(core.diagnosticStatus([ok,warning]),{latest:warning,count:2,status:'warning'});

  let tick=0;const calls=[];const fakeFetch=async(url,options={})=>{calls.push({url,method:options.method||'GET',bytes:options.body?.byteLength||0});return{ok:true,status:200,arrayBuffer:async()=>new ArrayBuffer(0)};};
  const speed=await core.runBrowserSpeedTest({fetch:fakeFetch,now:()=>{tick+=100;return tick;},downloadBytes:500000,uploadBytes:100000,timeoutMs:1000});
  assert.equal(speed.speedProvider,'Cloudflare');assert.equal(speed.speedStatus,'success');assert.ok(speed.downloadMbps>0);assert.ok(speed.uploadMbps>0);assert.ok(speed.latencyMs>0);assert.ok(speed.jitterMs!==null);assert.equal(calls.filter(item=>item.method==='POST').length,1);assert.equal(calls.find(item=>item.method==='POST').bytes,100000);
  const history=core.appendDiagnosticHistory([ok],core.makeDiagnosticRecord(speed,{id:'p'},new Date('2026-09-07T12:00:00Z')));assert.equal(history.length,2,'speed result appends and does not overwrite earlier diagnostics');assert.equal(history[1].result.speedStatus,'success');assert.equal(history[1].result.downloadMbps,speed.downloadMbps);
  assert.match(domain,/await toolsSaveCurrentDiagnostic\(\)/,'ticket-context speed result uses the existing append-only save path');assert.match(domain,/toolsSpeedController\?\.abort/);assert.match(domain,/timeoutMs:20000/);assert.match(html,/connect-src[^;]+https:\/\/speed\.cloudflare\.com/);assert.match(backup,/diagnostics:tools\.diagnostics/);assert.doesNotMatch(share,/diagnosticHistory|speedStatus|downloadMbps|uploadMbps/,'dispatcher payload remains free of diagnostics and speed results');
  console.log('PASS v91.9 mobile map controls, per-category marker preferences, autofill isolation, diagnostic status and append-only speed history');
})().catch(error=>{console.error(error);process.exitCode=1;});
