'use strict';
const {test,expect,gotoApp}=require('./app-test');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
test('AI network error is cleared by a successful ordinary send, without duplicate asks',async({page,appEnv})=>{
 let calls=0;
 await page.route('https://maister-tracker-mcp.mastif1235.workers.dev/ask',async route=>{
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'}});
  calls++;
  if(calls===1)return route.abort('failed');
  return route.fulfill({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({ok:true,answer:'Успішна відповідь.',meta:{}})});
 });
 await gotoApp(page,appEnv.url);
 await page.evaluate(async()=>{MTAI.storage.update({enabled:true,backendMode:'custom',backendUrl:MTAI.config.SHARED_BACKEND});MTAI.storage.setToken('synthetic-ai-test');await mtSettingsSecretsFlushPending();MTAI.ui.open();});
 const send=async text=>{await page.locator('#aiInput').fill(text);await page.locator('#aiSendBtn').click();await expect(page.locator('#aiSendBtn')).toBeEnabled();};
 await send('Перший запит');await expect(page.locator('.ai-msg-error')).toContainText('Немає з’єднання');
 await send('Наступний запит');await expect(page.locator('.ai-msg-assistant').last()).toContainText('Успішна відповідь');
 await expect(page.locator('.ai-msg-error')).toHaveCount(0);expect(calls).toBe(2);
});
test('AI September -> August after reload keeps ONU all-install scope, coworker and both work types',async({page,appEnv})=>{
 const load=p=>import(pathToFileURL(path.join(__dirname,'../mcp/src/ask',p)).href);
 const {createAskOrchestrator}=await load('orchestrator.js'),{runSmartQuery}=await load('smart-query.js');
 const {TOOL_DEFINITIONS}=await import(pathToFileURL(path.join(__dirname,'../mcp/src/tools/definitions.js')).href);
 const tickets=[['SEPT','15.09.2026','Підключення'],['AUG_CONNECTION','15.08.2026','Підключення'],['AUG_REPAIR','18.08.2026','Ремонт']].map(([id,date,type])=>({id,date,type,tags:['Женя'],connectMasters:[],equipment:[{label:'ONU',qty:1}],note:'',cables:[]})),queries=[];
 const orch=createAskOrchestrator({toolDefs:TOOL_DEFINITIONS,groq:{chat(){throw new Error('No LLM reconstruction');}},tools:{query_tickets:async p=>{queries.push(p);return runSmartQuery({tickets,shifts:[],searchIndex:[]},p);}}});
 await page.route('https://maister-tracker-mcp.mastif1235.workers.dev/ask',async route=>{
  const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'};
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const body=route.request().postDataJSON(),result=await orch.handle(body.question,{now:new Date('2026-10-03'),...body.context});
  return route.fulfill({status:200,contentType:'application/json',headers,body:JSON.stringify(result)});
 });
 await gotoApp(page,appEnv.url);
 await page.evaluate(async()=>{MTAI.storage.update({enabled:true,backendMode:'custom',backendUrl:MTAI.config.SHARED_BACKEND});MTAI.storage.setToken('synthetic-ai-test');await mtSettingsSecretsFlushPending();MTAI.ui.open();});
 await page.locator('#aiInput').fill('Сколько ONU я поставил с Женей за сентябрь?');await page.locator('#aiSendBtn').click();await expect(page.locator('.ai-msg-assistant').last()).toContainText('1 ONU');
 await page.reload();await page.waitForFunction(()=>window.__mtAppInitDone===true);await page.evaluate(()=>MTAI.ui.open());
 await page.locator('#aiInput').fill('А в августе?');await page.locator('#aiSendBtn').click();await expect(page.locator('.ai-msg-assistant').last()).toContainText('2 ONU');
 const q=queries.at(-1);expect(q.coworker).toBe('Женя');expect(q.semantic).toEqual(queries[0].semantic);expect(q.type).toBeUndefined();expect(q.date_from).toBe('01.08.2026');expect(q.date_to).toBe('31.08.2026');expect(q.mode).toBe('count');
 await expect(page.locator('.ai-msg-error')).toHaveCount(0);
});
test('AI work analytics: real deterministic Worker modules, count -> evidence -> reload preserves filter',async({page,appEnv})=>{
  const load=p=>import(pathToFileURL(path.join(__dirname,'../mcp/src/ask',p)).href);
  const {createAskOrchestrator}=await load('orchestrator.js');
  const {runSmartQuery}=await load('smart-query.js');
  const {TOOL_DEFINITIONS}=await import(pathToFileURL(path.join(__dirname,'../mcp/src/tools/definitions.js')).href);
  const texts=['Установил ONU, сигнал -21','Сигнал ONU -29','Проверил ONU','Заменил БП ONU','Заменил ONU','Поставил ONU и роутер','С Петей подключили абонента, поставили ONU и роутер','ONU клиента, сигнал -25',''];
  const tickets=texts.map((text,i)=>({id:'ABCDEFGHI'[i],date:'15.09.2026',time:'10:00',sum:100,type:i===6||i===8?'Підключення':'Ремонт',macAddress:i===6||i===8?'001122334455':'',connectMasters:i===6?['Петя']:[],equipment:[],cables:[],presetWorks:[],additionalWork:[],tags:i===8?['Петя','Артем']:[]}));
  const ctx={tickets,shifts:[{date:'15.09.2026',coworker:'Женя',hours:8}],searchIndex:texts.map((text,i)=>({id:tickets[i].id,text}))};
  const queries=[];
  const orch=createAskOrchestrator({groq:{chat(){throw new Error('No approximate LLM counts');}},tools:{query_tickets:async p=>{queries.push(p);return runSmartQuery(ctx,p);}},toolDefs:TOOL_DEFINITIONS});
  await page.route('https://maister-tracker-mcp.mastif1235.workers.dev/ask',async route=>{
    const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'};
    if(route.request().method()==='OPTIONS') return route.fulfill({status:204,headers});
    const body=route.request().postDataJSON();
    expect(body.context.coworkerRoster).toContain('Петя');
    const result=await orch.handle(body.question,{now:new Date(2026,9,2,12),...body.context});
    await route.fulfill({status:200,contentType:'application/json',headers,body:JSON.stringify(result)});
  });
  await page.setViewportSize({width:320,height:740});await gotoApp(page,appEnv.url);
  // localhost deliberately chooses the dev shared backend on boot. Pin only
  // this synthetic fixture's custom URL so reload keeps using our mock.
  await page.evaluate(async()=>{MTAI.storage.update({enabled:true,showInTools:true,backendMode:'custom',backendUrl:MTAI.config.SHARED_BACKEND});MTAI.storage.setToken('synthetic-ai-test');await mtSettingsSecretsFlushPending();MTAI.ui.open();});
  await page.locator('#aiInput').fill('Сколько ONU поставил с Петей в сентябре?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('2 ONU');
  await expect(page.locator('.ai-msg-assistant').last()).not.toContainText('business-derived');
  await page.getByRole('button',{name:'Показати заявки',exact:true}).click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Підключення з підтвердженим обладнанням');
  const exactFilters=query=>Object.fromEntries(['semantic','date_from','date_to','coworker'].map(key=>[key,query[key]]));
  expect(exactFilters(queries[1])).toEqual(exactFilters(queries[0]));
    expect(queries[1].coworker).toBe('Петя');
  expect(queries[1].semantic.profile).toBe('onu_physical');
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Майстер прямо вказаний у заявці');
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Майстер вказаний в історичному тезі самої заявки');
  await expect(page.locator('.ai-msg-assistant').last()).not.toContainText('001122334455');
  await expect(page.locator('#aiSendBtn')).toBeEnabled();
  await page.locator('#aiInput').fill('Почему так посчитано?');await page.locator('#aiSendBtn').click();
  await expect.poll(()=>queries.length).toBe(3);
  await expect(page.locator('#aiSendBtn')).toBeEnabled();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Подключение с подтверждённым оборудованием');
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('историческом теге самой заявки');
  expect(exactFilters(queries[2])).toEqual(exactFilters(queries[0]));
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.reload();await page.waitForFunction(()=>window.__mtAppInitDone===true);
  expect(await page.evaluate(()=>MTAI.storage.get().backendUrl)).toBe('https://maister-tracker-mcp.mastif1235.workers.dev');
  await page.evaluate(()=>MTAI.ui.open());
  await page.locator('#aiInput').fill('Чому так пораховано?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Підключення з підтвердженим обладнанням');
  expect(exactFilters(queries[3])).toEqual(exactFilters(queries[0]));
  await page.locator('#aiInput').fill('Сколько ONU было в сентябре?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Що рахувати');
});

test('AI physical consumption: free structured router, work-type filter and reload retain exact profile',async({page,appEnv})=>{
  const load=p=>import(pathToFileURL(path.join(__dirname,'../mcp/src/ask',p)).href);
  const {createAskOrchestrator}=await load('orchestrator.js'),{runSmartQuery}=await load('smart-query.js');
  const {TOOL_DEFINITIONS}=await import(pathToFileURL(path.join(__dirname,'../mcp/src/tools/definitions.js')).href);
  const tickets=[{id:'FREE_REPAIR',date:'15.09.2026',type:'Ремонт',sum:0,equipment:[{label:'Роутер',qty:1,price:0}],cables:[],tags:[],connectMasters:[]},{id:'CONNECTION',date:'15.09.2026',type:'Підключення',sum:100,equipment:[{label:'Роутер',qty:1,price:100}],cables:[{label:'UTP',meters:35}],tags:[],connectMasters:[]}];
  const ctx={tickets,shifts:[],searchIndex:[]},queries=[];
  const orch=createAskOrchestrator({groq:{chat(){throw new Error('No LLM counts');}},tools:{query_tickets:async p=>{queries.push(p);return runSmartQuery(ctx,p);}},toolDefs:TOOL_DEFINITIONS});
  await page.route('https://maister-tracker-mcp.mastif1235.workers.dev/ask',async route=>{
    const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'};
    if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
    const body=route.request().postDataJSON(),result=await orch.handle(body.question,{now:new Date('2026-10-03T12:00:00Z'),...body.context});
    await route.fulfill({status:200,contentType:'application/json',headers,body:JSON.stringify(result)});
  });
  await page.setViewportSize({width:320,height:740});await gotoApp(page,appEnv.url);
  await page.evaluate(async()=>{MTAI.storage.update({enabled:true,showInTools:true,backendMode:'custom',backendUrl:MTAI.config.SHARED_BACKEND});MTAI.storage.setToken('synthetic-ai-test');await mtSettingsSecretsFlushPending();MTAI.ui.open();});
  await page.locator('#aiInput').fill('Сколько роутеров поставил на ремонтах за сентябрь?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Роутер — 1 шт.');
  expect(queries[0].type).toBe('Ремонт');expect(queries[0].semantic.profile).toBe('physical_consumption');
  await page.getByRole('button',{name:'Показати заявки',exact:true}).click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Обладнання вказано в заявці');
  const exact=q=>Object.fromEntries(['type','semantic','date_from','date_to'].map(k=>[k,q[k]]));expect(exact(queries[1])).toEqual(exact(queries[0]));
  await page.reload();await page.waitForFunction(()=>window.__mtAppInitDone===true);await page.evaluate(()=>MTAI.ui.open());
  await page.locator('#aiInput').fill('Почему так посчитано?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Роутер — 1 шт.');expect(exact(queries[2])).toEqual(exact(queries[0]));
  await page.locator('#aiInput').fill('Сколько всего материалов списать за сентябрь?');await page.locator('#aiSendBtn').click();
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Роутер — 2 шт.');
  await expect(page.locator('.ai-msg-assistant').last()).toContainText('Кабель — 35 м');
  expect(queries[3].mode).toBe('group');expect(queries[3].group_by).toBe('entity');expect(queries[3].type).toBeUndefined();
  await expect(page.locator('#aiSendBtn')).toBeEnabled();
});

test('AI v91.83: fresh date selection -> card -> reload -> same profile card, never broad list',async({page,appEnv})=>{
 const load=p=>import(pathToFileURL(path.join(__dirname,'../mcp/src/ask',p)).href);
 const {createAskOrchestrator}=await load('orchestrator.js'),{runSmartQuery}=await load('smart-query.js');
 const {TOOL_DEFINITIONS}=await import(pathToFileURL(path.join(__dirname,'../mcp/src/tools/definitions.js')).href);
 const ticket={id:'SYNTHETIC_REPAIR',date:'18.09.2026',time:'12:44',type:'Ремонт',city:'Тестове',street:'Вул Садова',house:'106',apartment:'29',sum:0,equipment:[{label:'ONU',qty:1}],note:'На старой ONU жужжат дросселя',connectMasters:['Женя'],tags:[]};
 let modelRound=0;const requests=[];
 const orch=createAskOrchestrator({toolDefs:TOOL_DEFINITIONS,tools:{query_tickets:async p=>runSmartQuery({tickets:[ticket],shifts:[],searchIndex:[]},p)},groq:{chat:async()=>modelRound++?{ok:true,content:'Відкриваю заявку.',toolCalls:[],assistantMessage:{role:'assistant',content:'Відкриваю заявку.'}}:{ok:true,content:'',toolCalls:[{id:'read',name:'query_tickets',argsRaw:JSON.stringify({mode:'list',date_from:ticket.date,date_to:ticket.date})}],assistantMessage:{role:'assistant',content:'',tool_calls:[]}}}});
 await page.route('https://maister-tracker-mcp.mastif1235.workers.dev/ask',async route=>{
  const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'};
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const body=route.request().postDataJSON();requests.push(body);
  const result=await orch.handle(body.question,{now:new Date('2026-10-03'),...body.context});
  await route.fulfill({status:200,contentType:'application/json',headers,body:JSON.stringify(result)});
 });
 await page.setViewportSize({width:320,height:740});await gotoApp(page,appEnv.url);
 const localTicket=async()=>page.evaluate(t=>{tickets.push(t);},ticket);
 await localTicket();
 await page.evaluate(async()=>{MTAI.storage.update({enabled:true,showInTools:true,backendMode:'custom',backendUrl:MTAI.config.SHARED_BACKEND});MTAI.storage.setToken('synthetic-ai-test');await mtSettingsSecretsFlushPending();MTAI.ui.open();});
 const send=async text=>{await page.locator('#aiInput').fill(text);await page.locator('#aiSendBtn').click();await expect(page.locator('#aiSendBtn')).toBeEnabled();};
 await send('Открой заявку за 18.09.2026');
 await expect(page.locator('[data-ai-ticket-card="SYNTHETIC_REPAIR"]')).toHaveCount(1);
 await send('Открой карточку');expect(requests.at(-1).context.selectedTicketId).toBe(ticket.id);
 await expect(page.locator('.ai-msg-assistant').last().locator('[data-ai-ticket-card="SYNTHETIC_REPAIR"]')).toHaveCount(1);
 await page.reload();await page.waitForFunction(()=>window.__mtAppInitDone===true);await localTicket();await page.evaluate(()=>MTAI.ui.open());
 await send('Открой профиль');expect(requests.at(-1).context.selectedTicketId).toBe(ticket.id);
 await expect(page.locator('.ai-msg-assistant').last().locator('[data-ai-ticket-card="SYNTHETIC_REPAIR"]')).toHaveCount(1);
 await expect(page.locator('.ai-msg-assistant').last().getByRole('button',{name:'👤 Відкрити профіль',exact:true})).toBeVisible();
 expect(modelRound).toBe(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
